# Generated by Django 5.1.4 on 2025-01-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
