# Generated by Django 5.1.1 on 2025-05-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0003_album_cover_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMG', 'Image'), ('TXT', 'Text'), ('STCKR', 'Sticker')], max_length=5)),
                ('content', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='scrapbook.page')),
            ],
        ),
    ]
