# Generated by Django 5.1.1 on 2025-06-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0004_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='albumID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='scrapbook.album'),
        ),
    ]
