# Generated by Django 5.1.1 on 2025-06-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0006_rename_albumid_media_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='pageID',
            new_name='page',
        ),
    ]
