# Generated by Django 5.1.1 on 2025-06-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0007_rename_pageid_media_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='x',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='y',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
