# Generated by Django 5.1.1 on 2025-06-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0009_alter_media_height_alter_media_width_alter_media_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='height',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='width',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='x',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='media',
            name='y',
            field=models.FloatField(default=200),
        ),
    ]
